version: '3.3'

services:
  mariadb: 
    image: wodby/mariadb:10.1-2.1.0
    ports:
        - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=drupal
      - MYSQL_USER=drupal
      - MYSQL_PASSWORD=drupal
  php: 
    image: wodby/drupal-php:7.1-2.1.0
    depends_on:
      - mariadb
    volumes:
      - ./:/var/www/html
  nginx:
    image: wodby/drupal-nginx:8-1.10-2.1.0
    depends_on:
      - php
    ports: 
      - 8080:80
    environment:
      NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html
    volumes:
      - ./:/var/www/html
